version: '3.8'
services:
        movie-analyst-ui:
                build: ./ui
                image: ${UI_IMAGE}
                
                environment:
                        - BACKEND_URL=${BACKEND_URL}
                        - FRONTEND_PORT=${FRONTEND_PORT}
                env_file:
                        - .env
                container_name: ${UI_CONTAINER}
                ports:
                        - "80:8000"
                restart: unless-stopped
                
                healthcheck:
                        test: curl --fail http://localhost || exit 1
                        interval: 60s
                        retries: 5
                        start_period: 150s
                        timeout: 10s
